version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - type: volume
        source: data
        target: /data/db
    # environment:
    #   - MONGODB_USERNAME=veronican
    #   - MONGODB_PASSWORD=secret
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - type: volume
        source: logs
        target: /app/logs
      - ./backend:/app
      - /app/node_modules 
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
        build: ./frontend
        volumes:
          - ./frontend/src:/app/src
        ports: 
          - '3000:3000'
        stdin_open: true
        tty: true
        depends_on:
          - backend
volumes:
  data:
  logs:
    
